services:
    valheim:
        image: faulo/farah:8.0
        volumes:
            - ./composer.json:/var/www/composer.json
            - ./composer.lock:/var/www/composer.lock
            - type: bind
              source: ./assets
              target: /var/www/assets
              read_only: true
              bind:
                  create_host_path: true
            - type: bind
              source: ./src
              target: /var/www/src
              read_only: true
              bind:
                  create_host_path: true
            - type: bind
              source: ./html
              target: /var/www/html
              read_only: true
              bind:
                  create_host_path: true
            - type: bind
              source: ./data
              target: /var/www/data
              read_only: false
              bind:
                  create_host_path: true
            - type: bind
              source: ./log
              target: /var/www/log
              read_only: false
              bind:
                  create_host_path: true
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
    server:
        image: lloesche/valheim-server:latest
        cap_add:
            - SYS_NICE
        environment:
            - SERVER_NAME=Slothsoft
            - SERVER_PASS=slothsoft.net
            - WORLD_NAME=Eternia
        volumes:
            - type: bind
              source: ./server-config
              target: /config
              read_only: false
              bind:
                  create_host_path: true
            - type: bind
              source: ./server-data
              target: /opt/valheim
              read_only: false
              bind:
                  create_host_path: true
        ports:
            - 2456-2457:2456-2457/udp
            - 2456-2457:2456-2457/tcp
        networks:
            - vhosts_default
networks:
    vhosts_default:
        external: true