services:
    frontend:
        container_name: ${STACK_NAME}_frontend
        build:
            dockerfile: Dockerfile.linux
            args:
                PHP_VERSION: ${PHP_VERSION}
        environment:
            SERVER_NAME: ${SERVER_NAME}
            VIRTUAL_HOST: ${SERVER_NAME}
            LETSENCRYPT_HOST: ${SERVER_NAME}
        volumes:
            - /var/vhosts/${SERVER_NAME}/:/var/www/data/
        networks:
            - vhosts
        expose:
            - 80
        restart: unless-stopped

    world:
        container_name: ${STACK_NAME}_world
        image: lloesche/valheim-server:latest
        cap_add:
            - SYS_NICE
        environment:
            - SERVER_NAME: Slothsoft
            - SERVER_PORT: 2456
            - SERVER_PASS: slothsoft.net
            - SERVER_PUBLIC: false
            - WORLD_NAME: Eternia
        volumes:
            - /var/vhosts/${SERVER_NAME}/server-config:/config
            - /var/vhosts/${SERVER_NAME}/server-data:/opt/valheim
        ports:
            - 2456-2457:2456-2457/udp
            - 2456-2457:2456-2457/tcp
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        restart: unless-stopped

networks:
    vhosts:
        external: true

